export enum CATEGORYTYPE {
  DOVIZ = 'DOVIZ',
  // ZIYNET = 'ZIYNET',
  PARITE = 'PARITE',
  SARRAFIYE = 'SARRAFIYE',
  GRAM = 'GRAM',
  EKRAN = 'EKRAN',
  // KUYUMCU = 'KUYUMCU',
  // GRAMALTIN = 'GRAM ALTIN',
  // PERAKENDE = 'PERAKENDE',
}
